// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATgSEKJAg4K9zWWpCHeTc4J46pieVRZUc',
    appId: '1:640527448343:android:679b12b63b912f293e5f52',
    messagingSenderId: '640527448343',
    projectId: 'mis-proekt-24a3b',
    storageBucket: 'mis-proekt-24a3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfC1lyrXeDHpKna7oJfNaQrg-VR7397aM',
    appId: '1:640527448343:ios:df3ab41d04fbc4ca3e5f52',
    messagingSenderId: '640527448343',
    projectId: 'mis-proekt-24a3b',
    storageBucket: 'mis-proekt-24a3b.firebasestorage.app',
    iosBundleId: 'com.example.misProekt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ChyuO1BWWd20sfOSQYINaj_119aexZw',
    appId: '1:640527448343:web:69cb23fa5d3fc7453e5f52',
    messagingSenderId: '640527448343',
    projectId: 'mis-proekt-24a3b',
    authDomain: 'mis-proekt-24a3b.firebaseapp.com',
    storageBucket: 'mis-proekt-24a3b.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ChyuO1BWWd20sfOSQYINaj_119aexZw',
    appId: '1:640527448343:web:69cb23fa5d3fc7453e5f52',
    messagingSenderId: '640527448343',
    projectId: 'mis-proekt-24a3b',
    authDomain: 'mis-proekt-24a3b.firebaseapp.com',
    storageBucket: 'mis-proekt-24a3b.firebasestorage.app',
  );

}